# PingPongOS - PingPong Operating System
# Prof. Carlos A. Maziero, DINF UFPR
# Versão 2.0 -- Junho de 2025

# ATENÇÃO: ESTE ARQUIVO NÃO DEVE SER ALTERADO;
# ALTERAÇÕES SERÃO DESCARTADAS NA CORREÇÃO.

# flags
CPPFLAGS += -I../ -I../kernel/ -I../lib/

# compila arquivo de teste
ping%:
	$(CC) $(CFLAGS) $(CPPFLAGS) -c -o $@.o $@.c 
